package cn.wanyj.codefreex.service.impl;

import cn.wanyj.codefreex.common.AppConstant;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.Resource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.zip.ZipFile;
import java.util.zip.ZipInputStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * @author BanXia
 */
class AppStorageServiceImplTest {

    private final AppStorageServiceImpl appStorageService = new AppStorageServiceImpl();
    private final String deployKey = "P6_STORAGE_TEST";

    @AfterEach
    void tearDown() throws IOException {
        deleteIfExists(Path.of(AppConstant.CODE_OUTPUT_ROOT_DIR, deployKey));
        deleteIfExists(Path.of(AppConstant.CODE_DEPLOY_ROOT_DIR, deployKey));
        deleteIfExists(Path.of(AppConstant.CODE_DOWNLOAD_ROOT_DIR, deployKey + ".zip"));
        deleteIfExists(Path.of(AppConstant.CODE_NGINX_ROOT_DIR));
    }

    @Test
    void loadGeneratedResource_emptyPath_returnsIndexHtml() throws Exception {
        Path dir = Path.of(AppConstant.CODE_OUTPUT_ROOT_DIR, deployKey);
        Files.createDirectories(dir);
        Files.writeString(dir.resolve("index.html"), "<html>preview</html>");

        Resource resource = appStorageService.loadGeneratedResource(deployKey, "");

        assertThat(resource.getContentAsString(java.nio.charset.StandardCharsets.UTF_8))
                .contains("preview");
    }

    @Test
    void copyGeneratedToDeployed_andCreateDownloadArchive_workAsExpected() throws Exception {
        Path dir = Path.of(AppConstant.CODE_OUTPUT_ROOT_DIR, deployKey);
        Files.createDirectories(dir.resolve("assets"));
        Files.createDirectories(dir.resolve("node_modules"));
        Files.writeString(dir.resolve("index.html"), "<html>app</html>");
        Files.writeString(dir.resolve("assets").resolve("main.css"), "body{}");
        Files.writeString(dir.resolve("node_modules").resolve("skip.js"), "skip");

        appStorageService.copyGeneratedToDeployed(deployKey);
        Path zipPath = appStorageService.createDownloadArchive(deployKey, deployKey + ".zip");

        assertThat(Files.readString(Path.of(AppConstant.CODE_DEPLOY_ROOT_DIR, deployKey, "index.html")))
                .contains("app");

        try (ZipFile zipFile = new ZipFile(zipPath.toFile())) {
            assertThat(zipFile.getEntry("index.html")).isNotNull();
            assertThat(zipFile.getEntry("assets/main.css")).isNotNull();
            assertThat(zipFile.getEntry("node_modules/skip.js")).isNull();
        }

        Path unzipDir = Files.createTempDirectory("p6-unzip-");
        try {
            unzip(zipPath, unzipDir);
            assertThat(Files.readString(unzipDir.resolve("index.html"))).contains("app");
            assertThat(Files.readString(unzipDir.resolve("assets").resolve("main.css"))).contains("body");
        } finally {
            deleteIfExists(unzipDir);
        }
    }

    @Test
    void generateCover_createsPngFile() {
        Path dir = Path.of(AppConstant.CODE_DEPLOY_ROOT_DIR, deployKey);
        try {
            Files.createDirectories(dir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        String coverUrl = appStorageService.generateCover(deployKey, "Demo App", "Generated by test");

        assertThat(coverUrl).isEqualTo("/api/deploy/" + deployKey + "/cover.png");
        assertThat(Files.exists(dir.resolve("cover.png"))).isTrue();
    }

    @Test
    void generateNginxConfig_createsExpectedConfigFile() throws Exception {
        Path dir = Path.of(AppConstant.CODE_DEPLOY_ROOT_DIR, deployKey);
        Files.createDirectories(dir);
        Files.writeString(dir.resolve("index.html"), "<html>deploy</html>");

        Path configPath = appStorageService.generateNginxConfig(deployKey);

        assertThat(Files.exists(configPath)).isTrue();
        assertThat(Files.readString(configPath)).contains("server_name " + deployKey + ".local");
        assertThat(Files.readString(configPath)).contains("try_files $uri $uri/ /index.html;");
    }

    private void unzip(Path zipPath, Path targetDir) throws IOException {
        try (ZipInputStream zipInputStream = new ZipInputStream(Files.newInputStream(zipPath))) {
            java.util.zip.ZipEntry entry;
            while ((entry = zipInputStream.getNextEntry()) != null) {
                Path outputPath = targetDir.resolve(entry.getName()).normalize();
                if (entry.isDirectory()) {
                    Files.createDirectories(outputPath);
                } else {
                    Files.createDirectories(outputPath.getParent());
                    Files.copy(zipInputStream, outputPath);
                }
                zipInputStream.closeEntry();
            }
        }
    }

    private void deleteIfExists(Path path) throws IOException {
        if (!Files.exists(path)) {
            return;
        }
        if (Files.isRegularFile(path)) {
            Files.deleteIfExists(path);
            return;
        }
        try (var stream = Files.walk(path)) {
            stream.sorted(Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
}
