package cn.wanyj.codefreex.service.strategy.impl;

import cn.wanyj.codefreex.common.AppConstant;
import cn.wanyj.codefreex.model.enums.CodeGenType;
import cn.wanyj.codefreex.service.ProjectBuildService;
import cn.wanyj.codefreex.service.WorkflowFileToolService;
import cn.wanyj.codefreex.service.impl.FileBundleParser;
import cn.wanyj.codefreex.service.strategy.CodePersistStrategy;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

/**
 * Vue 工程持久化策略
 *
 * @author BanXia
 */
@Component
@RequiredArgsConstructor
public class VueProjectStrategy implements CodePersistStrategy {

    private final WorkflowFileToolService workflowFileToolService;
    private final ProjectBuildService projectBuildService;

    @Override
    public CodeGenType getCodeGenType() {
        return CodeGenType.VUE;
    }

    @Override
    public String persist(String deployKey, String code) {
        Path generatedRootDir = Path.of(AppConstant.CODE_OUTPUT_ROOT_DIR, deployKey);
        Path sourceDir = generatedRootDir.resolve("source");
        try {
            Files.createDirectories(sourceDir);
        } catch (Exception e) {
            throw new RuntimeException("创建 Vue 工程目录失败", e);
        }

        Map<String, String> fileMap = FileBundleParser.parse(code);
        if (fileMap.isEmpty()) {
            writeFallbackVueProject(sourceDir);
        } else {
            for (Map.Entry<String, String> entry : fileMap.entrySet()) {
                workflowFileToolService.writeFile(sourceDir, entry.getKey(), entry.getValue());
            }
        }
        projectBuildService.buildVueProject(generatedRootDir, progress -> {
        });
        return generatedRootDir.toString();
    }

    private void writeFallbackVueProject(Path sourceDir) {
        workflowFileToolService.writeFile(sourceDir, "package.json", """
                {
                  "name": "codefreex-vue-app",
                  "private": true,
                  "version": "1.0.0",
                  "type": "module",
                  "scripts": {
                    "build": "vite build"
                  },
                  "dependencies": {
                    "vue": "^3.5.0"
                  },
                  "devDependencies": {
                    "vite": "^5.4.0",
                    "@vitejs/plugin-vue": "^5.1.0"
                  }
                }
                """);
        workflowFileToolService.writeFile(sourceDir, "vite.config.js", """
                import { defineConfig } from 'vite'
                import vue from '@vitejs/plugin-vue'

                export default defineConfig({
                  plugins: [vue()],
                  build: {
                    outDir: 'dist'
                  }
                })
                """);
        workflowFileToolService.writeFile(sourceDir, "index.html", """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8" />
                  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                  <title>CodeFreeX Vue App</title>
                </head>
                <body>
                  <div id="app"></div>
                  <script type="module" src="/src/main.js"></script>
                </body>
                </html>
                """);
        workflowFileToolService.writeFile(sourceDir, "src/main.js", """
                import { createApp } from 'vue'
                import App from './App.vue'

                createApp(App).mount('#app')
                """);
        workflowFileToolService.writeFile(sourceDir, "src/App.vue", """
                <template>
                  <main class="app">
                    <h1>CodeFreeX Vue Workflow</h1>
                    <p>Fallback preview generated by workflow.</p>
                  </main>
                </template>

                <style scoped>
                .app {
                  min-height: 100vh;
                  display: grid;
                  place-items: center;
                  font-family: 'Segoe UI', sans-serif;
                }
                </style>
                """);
    }
}
